name: 'dev pipeline'

on:
  workflow_dispatch:
    inputs:
      tf-plan-only:
        description: 'run only plan'
        required: true
        default: true
        type: boolean

env:
  SUBSCRIPTION_NAME: "test_subscription"
  RESOURCE_GROUP_NAME: "terraform_actions_rg"
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_SP_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  initialization-job:
    name: "initial"
    runs-on : onprem-windows
    environment: dev
    outputs:
      formatResult: ${{ steps.terraformFormat.outcome }}
      subscriptionName: ${{ env.SUBSCRIPTION_NAME }}
      resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: terraform setup
        uses: hashicorp/setup-terraform@v2

      - name: fmt
        run: terraform -fmt -check -diff -recursive
        id: terraformFormat
        continue-on-error: true

      - name: display options
        id: displayInputOptions
        shell: pwsh
        run: |
          echo "tf-plan: ${{ inputs.tf-plan-only }}"
        continue-on-error: true

      
