name: 'dev pipeline'

on:
  workflow_dispatch:
    inputs:
      tf-plan-only:
        description: 'run only plan'
        required: true
        default: true
        type: boolean

env:
  SUBSCRIPTION_NAME: "test_subscription"
  RESOURCE_GROUP_NAME: "terraform_actions_rg"
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_SP_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  initialization-job:
    name: "initial"
    runs-on : onprem-windows
    environment: dev
    outputs:
      formatResult: ${{ steps.terraformFormat.outcome }}
      subscriptionName: ${{ env.SUBSCRIPTION_NAME }}
      resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: terraform setup
        uses: hashicorp/setup-terraform@v2

      - name: fmt
        run: terraform fmt -check -diff -recursive
        id: terraformFormat
        continue-on-error: true

      - name: display options
        id: displayInputOptions
        shell: powershell
        run: |
          echo "tf-plan: ${{ inputs.tf-plan-only }}"
        continue-on-error: true

  plan-job:
    #needs: [initialization-job]
    name: 'run terraform plan'
    runs-on: onprem-windows
    environment: dev
    if: ${{ inputs.tf-plan-only }}
    steps: 
      - name: az login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}", "clientSecret":"${{ secrets.AZURE_SP_SECRET }}", "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "tenantID": "${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: checkout repo
        uses: actions/checkout@v3

      #- name: set az account
      #  uses: Azure/cli
      #  with:
      #    inlineScript: |
      #      az account set --name ${{inputs.}}

      - name: verify account
        uses: Azure/cli@v1.0.7
        with:
          inlineScript:
            az account show

      - name: set login variables for terraform
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_SP_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

      - name: terraform setup
        uses: hashicorp/setup-terraform@v2

      - name: terraform init
        id: terraforminit
        run: terraform init

      - name: terrform plan
        id: terraformplan
        run: terraform plan
      
